- components/AddressInput.tsx
- components/Conversation/RecipientControl.tsx
- helpers/string.ts
- package-lock.json
- package.json
Just added a minor check on top of what @neekolas had built to make sure we pass the conversationId while creating a new conversation when it does exist.
> Fix issue with empty conversations

- helpers/fetchMostRecentMessage.ts
- helpers/getUniqueMessages.ts
- helpers/keys.ts
- helpers/string.ts
- helpers/tests/appVersion.test.ts
- helpers/tests/classNames.test.ts
- helpers/tests/env.test.ts
- helpers/tests/fetchMostRecentMessages.test.ts
- helpers/tests/getUniqueMessages.test.ts
- helpers/tests/keys.test.ts
- helpers/tests/string.test.ts
- jest.config.js
- jest.setup.ts
* Added final unit tests for all current utils 
* Updated tests for a couple of edge cases
> Unit Tests

- components/Conversation/Conversation.tsx
- components/Conversation/RecipientControl.tsx
- components/Conversation/tests/RecipientControl.cy.tsx
- components/NavigationPanel.tsx
- components/tests/Address.cy.tsx
- components/tests/AddressInput.cy.tsx
- components/tests/AddressPill.cy.tsx
- components/tests/App.cy.tsx
- components/tests/Avatar.cy.tsx
- components/tests/Layout.cy.tsx
- components/tests/NavigationPanel.cy.tsx
- components/tests/UserMenu.cy.tsx
- components/tests/XmtpInfoPanel.cy.tsx
- cypress/e2e/connect_disconnect.cy.ts
- cypress/mock_wagmi_client.ts
- cypress/test_utils.ts
- hooks/useHandleConnect.ts
- hooks/useWalletAddress.ts
* Updated component tests that were failing and 1 E2E test
* Fixed logic in useWallet hook
* Small bugfixes
> fixed component tests, small bugfixes for useWallet hook

- components/Conversation/RecipientControl.tsx
- components/ConversationsList.tsx
Fixes mobile view UI issues raised by Matt
Apart from the keypad issue overlapping with text input
> fixes mobile view issues

- package-lock.json
- package.json
This will include a fix to connect wallets via Ledger Live: https://github.com/xmtp/xmtp-js/pull/271.
> Upgrade xmtp-js to 7.10 to include ledger fix

- component-library/components/ExpandedWalletCard/ExpandedWalletCard.stories.tsx
- component-library/components/ExpandedWalletCard/ExpandedWalletCard.tsx
- component-library/components/HeaderDropdown/HeaderDropdown.tsx
- component-library/components/ProfileDropdown/ProfileDropdown.tsx
- component-library/components/SideNav/SideNav.tsx
- component-library/pages/MessagesPage/MessagesPage.stories.tsx
- component-library/pages/MessagesPage/MessagesPage.tsx
Added Modal support wherever required, also got MessagePage stories to work.
> Wip storybook bh

- package-lock.json
- package.json
Applies security patch, by bumping version to 7.13.1
> Bump version: xmtp-js: v7.13.1

- components/App.tsx
- helpers/constants.ts
This PR is just adding a simple log to confirm our new subdomain— where we deploy code merged to dev that points to prod chats for more accurate pre-prod testing — is working as expected.
> Alpha validation

- pages/index.tsx
> fixes refresh issue

- helpers/env.ts
- helpers/internalTracking.ts
- hooks/useSendMessage.ts
Fixing the wallet address being passed to the tracking event and not passing the conversation id
> minor issue regarding conversation id fixed

- wrappers/SideNavWrapper.tsx
> Fix manual disconnect from side bar

- component-library/components/MessageInput/MessageInput.tsx
> fixes issues with message input

- component-library/components/SideNav/SideNav.tsx
Small design fix to close #222.
> Fixes width of hover state

- cypress/e2e/messaging.cy.ts
- hooks/useInitXmtpClient.ts
- pages/index.tsx
This PR should fix the issue the reopened comment in #203 addresses, and close out this ticket.
> Reset status on onboarding page

- hooks/useGetMessages.ts
> added useMessages hook

- hooks/useGetMessages.ts
Reverts xmtp-labs/xmtp-inbox-web#233
> Revert "added useMessages hook"

- hooks/useInitXmtpClient.ts
- pages/inbox.tsx
- store/xmtp.tsx
> Update onboarding when wallet changes

- component-library/pages/ErrorPage/ErrorPage.tsx
- pages/404.tsx
This PR adds proper error handling for 404 errors and closes out issue https://github.com/xmtp-labs/xmtp-inbox-web/issues/250.
> Gracefully handle 404 errors

- hooks/useGetMessages.ts
Small PR to add checksum’d address support when pulling from a map of conversations, required for UNS changes.
> Fix for mixed case addresses

- component-library/components/MessageInput/MessageInput.stories.tsx
- component-library/components/MessageInput/MessageInput.tsx
- component-library/pages/MessagesPage/MessagesPage.tsx
- hooks/useAttachmentChange.tsx
- pages/inbox.tsx
- wrappers/MessageInputWrapper.tsx
This PR adds drag and drop functionality to image attachments.
Since we've temporarily disabled E2E tests, ran locally in meantime and tests are passing.
> Add drag and drop functionality

- component-library/components/RemoteAttachmentMessageTile/RemoteAttachmentMessageTile.tsx
- package-lock.json
- package.json
This PR adds the ability to zoom into image attachments. A very simple change thanks to a package. Screenshots below.
Since we've temporarily disabled E2E tests, validated that these pass locally.
https://github.com/xmtp-labs/xmtp-inbox-web/assets/35409260/a5316937-e389-4fb0-80b3-595308b10dea
> Added zoom-in capability for attachments

- package-lock.json
- package.json
Consuming latest JS SDK to prevent creation of mangled topics.
> Bumped React SDK version to consume 9.1.1 of js sdk

- hooks/useAttachmentChange.tsx
Additional image support for gifs.
> Added webp extn support

- .github/workflows/cypress.yml
> Reenabling e2e tests

- component-library/components/RemoteAttachmentMessageTile/RemoteAttachmentMessageTile.tsx
- helpers/attachments.ts
- helpers/tests/attachments.test.ts
- hooks/useAttachmentChange.tsx
- locales/en_US.json
- Updated file size support
- Auto-load all messages, even if not sent from self, assuming it's an appropriate file size
> Finishing touches on image attachments

- vercel.json
Reroute unknown routes to serve index.html. Fixes https://github.com/xmtp-labs/xmtp-inbox-web/issues/319
> Updated Vercel config

- src/component-library/components/MessageInput/MessageInput.tsx
Small fix so file input doesn't populate on mount.
> Added check for file input

- cypress/e2e/messaging.cy.ts
- cypress/test_utils.ts
- package-lock.json
- package.json
- src/component-library/components/FullConversation/FullConversation.tsx
- src/hooks/useGetMessages.ts
- src/hooks/useSendMessage.ts
Use the new `useCachedMessages` hook to enable message caching.
> Add message caching

- src/component-library/components/RemoteAttachmentMessageTile/RemoteAttachmentMessageTile.tsx
This was done in Lenster already for optimistic sending, but will provide a benefit here so that browser memory usage doesn't balloon if a user has a ton of images in their messages.
> Add Blob cache for remote attachments

- package-lock.json
- package.json
- src/component-library/components/FullMessage/FullMessage.stories.tsx
- src/component-library/components/MessageInput/MessageInput.tsx
- src/component-library/components/RemoteAttachmentMessageTile/RemoteAttachmentMessageTile.tsx
- src/controllers/MessageContentController.tsx
- src/controllers/MessageInputController.tsx
- src/helpers/attachments.ts
- src/helpers/recordingValue.ts
- src/helpers/tests/recordingValue.test.ts
- src/hooks/useAttachmentChange.tsx
- src/hooks/useInitXmtpClient.ts
- src/hooks/useRecordingTimer.tsx
- src/hooks/useSendMessage.ts
- src/hooks/useVoiceRecording.tsx
- src/locales/en_US.json
- src/pages/inbox.tsx
Added voice recording functionality through a custom hook and via `react-media-recorder`, which asks permission for mic on mount, then enables recording. 
While recording, displays a stopwatch with the recording length with an obvious red banner. Records on hold. Also, made some accessibility tweaks here so that the recording can also happen via keyboard, and some accessibility fixes to the other svgs that weren't yet keyboard-enabled. 
Updated to a smaller package to import the attachment types as well. 
**Via mouse (holding down):**
https://github.com/xmtp-labs/xmtp-inbox-web/assets/35409260/6df90eca-52e7-42f8-9ca3-2189163b48ee
**Via keyboard:**
https://github.com/xmtp-labs/xmtp-inbox-web/assets/35409260/1866a1ad-1687-49eb-a00a-617769aee27f
> Voice memos

- src/helpers/recordingValue.ts
Small fix to move seconds to show a placeholder 0 if < 10.
> Fixed seconds view

- src/component-library/components/MessageInput/MessageInput.tsx
- src/component-library/components/RemoteAttachmentMessageTile/RemoteAttachmentMessageTile.tsx
- src/helpers/recordingValue.ts
- src/hooks/useRecordingTimer.tsx
- src/locales/en_US.json
Fixes:
- Resets voice memo on X
- Error handling for gateway errors
> Gateway error handling

- src/controllers/MessagePreviewCardController.tsx
Log no longer needed; removing.
> Removed log

- package-lock.json
- package.json
- src/component-library/components/MessageInput/MessageInput.tsx
- src/hooks/useRecordingTimer.tsx
- src/hooks/useVoiceRecording.tsx
- src/locales/en_US.json
This PR includes 2 voice memo implementation changes:
* Removes hold to record functionality in favor of a start/stop icon 
* Adds a tooltip when mic is disabled indicating that mic access is needed
> Remove hold to start, add tooltip

- README.md
Replace with link to XMTP React playground app
> Remove link to xmtp-quickstart-react

- src/component-library/components/AddressInput/AddressInput.tsx
- src/component-library/components/MessageInput/MessageInput.tsx
- src/controllers/MessageContentController.tsx
Fixes for https://github.com/xmtp-labs/xmtp-inbox-web/issues/352 and https://github.com/xmtp-labs/xmtp-inbox-web/issues/333.
> Input focus and email link fixes

- src/component-library/components/HeaderDropdown/HeaderDropdown.tsx
- src/controllers/AddressInputController.tsx
- src/controllers/HeaderDropdownController.tsx
- src/pages/dm.tsx
- src/pages/inbox.tsx
Fixes to close an issue with the width of the message preview container on desktop as well as close out https://github.com/xmtp-labs/xmtp-inbox-web/issues/333 and https://github.com/xmtp-labs/xmtp-inbox-web/issues/351
> Small Fixes

- src/component-library/components/HeaderDropdown/HeaderDropdown.tsx
- src/controllers/HeaderDropdownController.tsx
Updated mobile view logic for fix for https://github.com/xmtp-labs/xmtp-inbox-web/issues/333
> Fix header component

- package-lock.json
- package.json
- src/controllers/AppController.tsx
- src/controllers/MessagePreviewCardController.tsx
- src/global.d.ts
- src/hooks/useGetRecipientInputMode.tsx
- src/hooks/useListConversations.tsx
- src/hooks/useStartFeedbackConvo.ts
- src/pages/dm.tsx
- src/pages/index.tsx
- vite.config.ts
In this PR:
* Upgraded to latest version of React SDK
* Applied fixes from latest SDK so that conversations are selected properly
* Fixed the `/dm` route to prevent global state reset
> Upgrade React SDK, fix conversation issues

- package-lock.json
- package.json
- src/helpers/keys.ts
- src/helpers/tests/keys.test.ts
- src/hooks/useInitXmtpClient.ts
Added snap logic to inbox — if snap is not installed but user can install it and is using Metamask, prompt them through the flow. If they reject it, redirect to old flow. If they accept it, install the snap to simplify future login flows.
> Add snaps flow

- src/controllers/SideNavController.tsx
- src/main.tsx
- src/pages/index.tsx
Extended wallets, removed disconnection from Wagmi as it was creating an issue that we'll be able to more easily fix in the upgrade migration.
> Extend wallets

- README.md
- cypress/e2e/connect_disconnect.cy.ts
- src/component-library/components/SideNav/SideNav.tsx
- src/locales/en_US.json
- src/locales/hi_IN.json
This PR removes coming soon buttons (full side nav removal pending some designs, but removing this in meantime as these aren't coming soon anymore).
Also updated README for the move from ethers --> viem.
> Remove "coming soon"

- src/hooks/useListConversations.tsx
- src/hooks/useStreamAllMessages.tsx
- src/main.tsx
in this PR:
* increased the DB version to ensure that the latest schema is recognized by clients that were using a previous version of the schema
* added check for Notification support before attempting to use the feature
> Fix blank screen on mobile, increase DB version

- src/controllers/AppController.tsx
in this PR:
* added redirect to `/` for undefined routes
> Redirect invalid routes to /

- src/component-library/components/FullMessage/FullMessage.tsx
Small fix to prevent pointer from showing when a user can't remove a reaction.
> Fixed cursor

- src/component-library/components/ReactionsBar/ReactionsBar.tsx
- src/locales/en_US.json
Separated out replies from regular reactions for more clarity per design direction.
> Cleaned up reactions bar

- package-lock.json
- package.json
- src/component-library/components/MessageInput/MessageInput.tsx
- src/component-library/components/ScreenEffects/RainEffect.tsx
- src/component-library/components/ScreenEffects/SnowEffect.tsx
- src/controllers/FullConversationController.tsx
- src/controllers/MessageInputController.tsx
- src/controllers/MessagePreviewCardController.tsx
- src/hooks/useSendMessage.ts
Removed unnecessary complexity coming from associated message.
> Associated message id --> message id

- package-lock.json
- package.json
- vite.config.ts
Updating version for consent capabilities.
> Bump React SDK

- package-lock.json
- package.json
- src/component-library/components/Frame/Frame.tsx
- src/controllers/FullMessageController.tsx
- src/helpers/getFrameInfo.ts
Adds current logic from frames client; subject to change, just to get an initial feel for frames in xmtp.chat.
> Add Frames client get/post logic

- package-lock.json
- package.json
- src/controllers/FullMessageController.tsx
Updated to align with changes [here](https://github.com/xmtp/xmtp-web/pull/179/files).
> Updated to latest frames client spec

- src/component-library/components/Frame/Frame.tsx
Making a PR directly to main for the styling updates from https://github.com/xmtp-labs/xmtp-inbox-web/pull/443, since there are other things in `dev` that we don't want to make their way into main
> Frames Styling updates to main

- package-lock.json
- package.json
- src/component-library/components/Frame/Frame.tsx
- src/controllers/FullMessageController.tsx
- src/helpers/frameInfo.ts
- src/helpers/openFrames.ts
* Upgraded `@xmtp/frames-client` and `@open-frames/proxy-client`
* Refactored types
* Allowed frames button `postUrl` to override frame `postUrl`
Resolves #461
> Support open frames button postUrl
