.github/workflows/cypress.yml
.github/workflows/lint.yml
.github/workflows/tests.yml
helpers/string.ts

This PR specifies the Node version to use during GitHub actions and enables caching of the `node_modules` directory.

Add setup-node to GitHub actions

---

components/Conversation/RecipientControl.tsx

The issue was that the conversationId being passed from XMTP was not null but incorrect, creating a bunch of empty conversations.
The fix is to replace the address and pass the conversation id, but this begs the question do we need a standard for the conversation id and have a couple of checks on the server side that makes sure this is followed because it is highly possible that conversationId being passed incorrectly can happen again if not on our app maybe some other app.

fixes conversationId issue creating empty conversations

---

component-library/components/DateDivider/DateDivider.tsx
component-library/components/FullConversation/FullConversation.tsx
component-library/components/HeaderDropdown/HeaderDropdown.tsx
component-library/components/IconButton/IconButton.tsx
component-library/components/MessageInput/MessageInput.tsx
component-library/components/MessagePreviewCard/MessagePreviewCard.tsx
component-library/components/SideNav/SideNav.tsx

**Design updates include:**
* Added border to side nav 
* Updated timestamp to only be on one line while still respecting max-w-md of the larger container
* Updated text to meet color-contrast requirement
* Fixed message input regression when entering large blocks of text

updated date to be on one line, fixed input regression

---

helpers/constants.ts
helpers/string.ts
helpers/tests/string.test.ts

It appears that support for `.cb.id` addresses got lost in the move between `example-chat-react` and `inbox-web` (it's missing from the first commit in this repo).
Added support back in and includes a test to avoid future regressions.

Bring back cb.id support

---

hooks/useInitXmtpClient.ts
package-lock.json
package.json

I was looking into the issue with Smurf Society, and noticed this in the console logs from prod. This should resolve the issue.

Specify env in canMessage call

---

component-library/components/AddressInput/AddressInput.tsx
component-library/components/MessageInput/MessageInput.tsx
component-library/components/OnboardingStep/OnboardingStep.tsx
pages/inbox.tsx

Adds some mobile styling tweaks:
- On iOS, font sizes below 16px trigger an auto-zoom, so set to 16px for mobile views only
- Fixes overlapping loader regression in mobile views
Updates address input to show purple background (all views, not just mobile), and adjusts some colors accordingly:

Updated mobile styling tweaks and added background for address input

---

component-library/components/AddressInput/AddressInput.tsx

For some reason, on some mobile browsers the hidden border of the address input element. was also hiding the text in its container. This PR adds back the border with a transparent background, so it still functions as expected.

Fixed border hiding text color

---

component-library/components/AddressInput/AddressInput.tsx

Previously we kept the address input background and border as static, this conditionally sets it to highlight when no address is resolved.

Updated address input

---

.dockerignore
.github/workflows/publish-docker.yml
docker/Dockerfile
docker/build
docker/buildx
docker/entrypoint.sh
docker/push
docker/run
hooks/useInitXmtpClient.ts

This PR adds support for passing the `NEXT_PUBLIC_XMTP_API_URL` env variable during build, adds a `Dockerfile` and some build scripts for it in `docker/`, and a GH workflow for auto building+publishing the container image. This is not intended for production builds, where we would just want to publish the static build via something like Vercel. The purpose of the container image is to allow for lightweight devnet/testnet deployments without requiring a new nextjs build for each. I tried to keep it all out of the way and in the `docker/` dir 😅

Support apiUrl from env and add auto-published dockerfile

---

.gitignore
docker/.env.default

This PR fixes this broken GH docker build/publish workflow: https://github.com/xmtp-labs/xmtp-inbox-web/actions/runs/4723655940/jobs/8379892640

build: add missing docker/.env.default

---

component-library/components/ConversationList/ConversationList.tsx
component-library/components/FullConversation/FullConversation.tsx
component-library/components/HeaderDropdown/HeaderDropdown.tsx
component-library/components/LearnMore/LearnMore.tsx
component-library/components/SideNav/SideNav.tsx
hooks/useGetRecipientInputMode.tsx
hooks/useInitXmtpClient.ts
hooks/useListConversations.tsx
hooks/useSendMessage.ts
hooks/useStreamAllMessages.tsx
next.config.js
package-lock.json
package.json
pages/_app.tsx
pages/inbox.tsx
pages/index.tsx
store/xmtp.tsx
wrappers/FullMessageWrapper..tsx
wrappers/SideNavWrapper.tsx

This PR begins the process of integrating the new React SDK into the Inbox app, starting with the provider and client.
* [Upgrade dependencies](https://github.com/xmtp-labs/xmtp-inbox-web/commit/be443ea2d06ab1fdf70340446c59565c94767f24): This commit upgrades to the latest versions of `wagmi`, `typescript`, `@rainbow-me/rainbowkit`, and the XMTP SDKs.
* [Disable ESM imports in Next.js](https://github.com/xmtp-labs/xmtp-inbox-web/commit/1bd65e3e4e25cab7da49bf7573866011d4be0a03): Unfortunately, Next.js has issues with ESM modules. This config update fixes the problem.
* [Wrap App with XMTPProvider](https://github.com/xmtp-labs/xmtp-inbox-web/commit/3215a620d05279d0d801304963b3a5f9dd343e7a): Necessary to access client anywhere
* [Fix console …

Start integrating React SDK

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/publish-docker.yml

We started seeing these ethersproject 401 errors when the container starts up, and we can see in the [build logs](https://github.com/xmtp-labs/xmtp-inbox-web/actions/runs/4758345809/jobs/8511577546) that it's showing the same thing. 
```
node:events:489
throw er; // Unhandled 'error' event
^
Error: Unexpected server response: 401
at ClientRequest.<anonymous> (/app/node_modules/@ethersproject/providers/node_modules/ws/lib/websocket.js:604:7)
at ClientRequest.emit (node:events:511:28)
at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
at TLSSocket.socketOnData (node:_http_client:535:22)
at TLSSocket.emit (node:events:511:28)
at addChunk (node:internal/streams/readable:332:12)
at readableAddChunk …
```

Include infura id during docker build

---

pages/_app.tsx

SDK stylesheet was pulled in which included some letter spacing styling we don't need in our app. Since we're only consuming the hooks from the SDK for now, commenting this out to close #221 and not risk design regressions from styles we're not yet using. 
Separately, updated the letter spacing issue directly to SDK here: https://github.com/xmtp/xmtp-web/pull/28

Remove SDK Styling

---

component-library/components/FullMessage/FullMessage.tsx
cypress/e2e/messaging.cy.ts
cypress/test_utils.ts
pages/index.tsx
wrappers/MessageContentWrapper.tsx

This PR makes a small change to the onDisconnect callback, ensuring the XMTP client is fully disconnected before proceeding to wipe keys, disconnect Wagmi, etc. This helps avoid potential race conditions and ensures a clean disconnect sequence.
Also updates Cypress tests to stabilize our messaging tests. Specifically needed to update a `data-testid` which seems to have moved with the addition of Interweave or the element we needed wasn't always found, and moved a click event out of our beforeEach hook and within the tests at the places they're needed.

Updated disconnect callback on onboarding page

---

pages/dm/[...recipientWalletAddr].tsx
pages/dm/index.tsx

Fixes #183 
This is only to enable dm route, so now once we have a share qr option, people can, for example, click on xmtp.chat/dm/montez.eth and be navigated to a conversation with montez, or start a conversation with him, we still won't have routes because that is causing other issues, the only route will be inbox.
CC - @snormore @eleanorhofstedt @petermdenton @yash-luna

Enable dm route

---

.github/workflows/publish-docker.yml
docker/Dockerfile
docker/build

This is failing [in the GH workflow](https://github.com/xmtp-labs/xmtp-inbox-web/actions/runs/4820195805/jobs/8585117220) but not when running locally via `docker/build`, and I'm not sure why yet, but it should be failing, and it does fail locally when running `npm run build` without `NEXT_PUBLIC_INFURA_ID` being available. So this PR fixes the failing GH workflow by including the infura ID env. It's a different infura ID than we use for the production deployments though, since these docker images are used for devnets.

Include infura id env in docker build

---

pages/inbox.tsx
store/xmtp.tsx

When switching between Metamask accounts, previous messages were populating due to a partial disconnect. This should fix that and close https://github.com/xmtp-labs/xmtp-inbox-web/issues/216.

Bugfix for wallet switching

---

helpers/string.ts
helpers/tests/string.test.ts
hooks/useGetMessages.ts

This PR includes a fix for non-null convoId conversations, where the Ethers checksum address formatting doesn't work with that format and throws an error. Wrapping this logic in a try/catch instead of using the previous nullish coalescing operator logic.

Added try/catch for ethers check

---

component-library/components/FullMessage/FullMessage.tsx
component-library/components/MessageInput/MessageInput.tsx
component-library/components/RemoteAttachmentMessageTile/RemoteAttachmentMessageTile.tsx
db.ts
package-lock.json
package.json

This PR includes caching for images that have already been loaded, so they don't have to be prompted with a "click to reload" each time.
Also tacking on some small changes to this PR:
* Removing "Image" text next to timestamp. 
* Updated some things for a11y like alt tags and aria-labels
While our E2E tests are temporarily disabled, just going to add a note in all my PR overviews a confirmation that these pass locally.

Added image caching with dexie

---

.dockerignore
docker/Dockerfile

Fixes the docker build failure in https://github.com/xmtp-labs/xmtp-inbox-web/pull/313

Use vite output dir in docker build

---

src/component-library/components/IconButton/IconButton.tsx
src/component-library/components/MessageInput/MessageInput.tsx
src/component-library/components/RemoteAttachmentMessageTile/RemoteAttachmentMessageTile.tsx
src/helpers/attachments.ts
src/helpers/tests/attachments.test.ts
src/hooks/useAttachmentChange.tsx
src/hooks/useSendMessage.ts
src/locales/en_US.json

This PR is broken down into 2 commits:
1) Initial setup to be able to add documents and videos within our current design. 
2) Updating the message input to show this in a more visually appealing way.

Initial support for documents and videos

---

src/component-library/components/Avatar/Avatar.tsx
src/controllers/MessageContentController.tsx

This PR includes 2 small fixes for the following:
- The Interweave library we use for rendering message content had `{validateTLD: false}` set, which disables top-level domain validation for URLs. This means URLs with invalid TLDs (like .example) were rendered as links. This PR fixes that and closes #280 
- `min-width` needed to be specified to close out #283

Updated avatar and link fixes

---

package-lock.json
package.json
patches/web3.storage+4.5.4.patch

Unfortunately, the `web3.storage` package doesn't properly export its types.
This PR patches `package.json` of `web3.storage` to export the types while we wait for the [official patch](https://github.com/web3-storage/web3.storage/pull/2278) to land.

Fix `web3.storage` types

---

src/component-library/components/RemoteAttachmentMessageTile/RemoteAttachmentMessageTile.tsx
src/helpers/attachments.ts
src/helpers/tests/attachments.test.ts
src/hooks/useAttachmentChange.tsx

Fixes a couple of issues with attachments:
- Messages initiated from Converse were showing up as blank; that was due to them being slightly over the file size we support and the "file too large" logic only showing for received messages. Now, we auto-load all sent messages even if over the size limit, and bumped the size limit of images sent from this app or auto-loaded received images to 10MB.
- Also fixed an issue discovered in the process to remove case sensitivity of extensions.

Attachment fixes

---

.github/workflows/cypress.yml
package-lock.json
package.json
src/global.d.ts
src/main.tsx

Bumps version and adds required project ID field for v2 compatibility.

Bumped RainbowKit version for WC v2 support

---

src/controllers/MessagePreviewCardController.tsx
src/hooks/useVoiceRecording.tsx

This PR removes the ask permission mic on mount check which showed a recording icon when it was not yet recording. It now asks permission only upon pressing the microphone icon, which would be the expected behavior.
Also added a log per a request for this.

Fix recording icon on mount, add log

---

src/controllers/ConversationListController.tsx
src/controllers/FullConversationController.tsx
src/controllers/MessagePreviewCardController.tsx
src/helpers/conversation.ts
src/helpers/string.ts
src/helpers/tests/string.test.ts
src/hooks/useAddressInput.ts
src/hooks/useStreamAllMessages.tsx

In this PR:
* Separated peer address name and avatar cache
* Added support all ENS names
* Fixed initial conversation peer address lookups

Refactor ENS/UNS lookups

---

src/component-library/components/FullConversation/FullConversation.stories.tsx
src/component-library/components/MessageInput/MessageInput.tsx
src/controllers/AddressInputController.tsx
src/controllers/MessagePreviewCardController.tsx
src/helpers/conversation.ts

in this PR:
* fixed type issues in `FullConversation.stories.tsx`
* refactored UNS/ENS name and avatar lookups to account for multiple conversations with the same peer address
* updated logic for selecting conversations to account for multiple conversations with the same peer address

Fix for multiple convos with the same peer address

---

src/controllers/MessagePreviewCardController.tsx
src/locales/en_US.json

Fixed issue with the previews during react/unreact.

Fixed reaction preview

---

src/component-library/components/AddressInput/AddressInput.tsx

Fixed bug where a resolved address was superseding error subtext, therefore displaying the resolved address instead of the expected error message for users not yet connected to the network.

Bugfix: subtext and resolved address check

---

src/hooks/useAddressInput.ts

when ENS/UNS name lookups fails, this change will set the state to `invalid`, clearing the loading state and displaying an appropriate message.

Set `invalid` state when name lookups fail

---

src/component-library/components/AddressInput/AddressInput.tsx

Dev --> Main

---

package-lock.json
package.json
src/global.d.ts
src/helpers/attachments.ts
src/hooks/useSendMessage.ts

This PR updates our current web3 storage upload logic to the new w3up API. 
Can send new attachments:
Can still view old attachments:

Updated image uploads for new Web3 Storage upload api

---

package-lock.json
package.json
src/component-library/components/Frame/Frame.tsx
src/controllers/FullMessageController.tsx
src/helpers/getFrameInfo.ts
src/helpers/openFrames.ts

- Uses latest `@xmtp/frames-client`
- Adds support for proxying images
- Adds support for `post_redirect` action types
- Adds support for `link` action types
- Fix bug where new clients were being created when Frames buttons are clicked, causing signatures

Upgrade Frames Client

---

src/component-library/components/AddressInput/AddressInput.tsx
src/component-library/components/HeaderDropdown/HeaderDropdown.tsx
src/component-library/components/LearnMore/LearnMore.tsx
src/component-library/components/MessageInput/MessageInput.tsx
src/component-library/components/Mobile/Mobile.tsx
src/controllers/AddressInputController.tsx
src/controllers/ConversationListController.tsx
src/controllers/HeaderDropdownController.tsx
src/controllers/MessagePreviewCardController.tsx
src/locales/en_US.json
src/pages/inbox.tsx

This PR removes mobile-specific logic in the app and adds a landing page for mobile users (based on breakpoint not user agent) to redirect them to the appropriate place.
Also removes unneeded code related to universal block/allow.

Remove mobile logic, redirect mobile users
